# Generated by Django 6.1.1 on 2026-09-16 01:23

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_quiz_ownership(apps, schema_editor):
    Quiz = apps.get_model("quizzes", "Quiz")
    Topic = apps.get_model("subjects", "Topic")

    for quiz in Quiz.objects.select_related("lesson__subject"):
        subject = quiz.lesson.subject
        question = quiz.quiz_questions.filter(
            question__lesson_id=quiz.lesson_id,
            question__topic__isnull=False,
        ).select_related("question__topic").first()
        topic_name = quiz.lesson.section_title or "General"
        topic_slug = slugify(topic_name) or "general"
        if question:
            topic_name = question.question.topic.name
            topic_slug = question.question.topic.slug
        topic, _ = Topic.objects.get_or_create(
            subject_id=subject.id,
            slug=topic_slug,
            defaults={"name": topic_name},
        )
        quiz.subject_id = subject.id
        quiz.topic_id = topic.id
        quiz.save(update_fields=["subject", "topic"])


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_subject_question_topic'),
        ('quizzes', '0001_initial'),
        ('subjects', '0002_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="subjects.subject",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="subjects.topic",
            ),
        ),
        migrations.RunPython(populate_quiz_ownership, migrations.RunPython.noop),
    ]
