# Generated by Django 6.1.1 on 2026-10-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('questions', '0004_answer_match_text_question_expected_answer_and_more'),
        ('quizzes', '0004_quiz_is_mock_quiz_time_limit_minutes_and_more'),
        ('subjects', '0003_topic_exam_weight'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('is_mock', True), models.Q(('topic__isnull', False), ('lesson__isnull', False)), _connector='OR'), name='quiz_non_mock_requires_topic_lesson'),
        ),
    ]
