# Generated by Django 6.1.1 on 2026-10-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_flashcardstate_mistakereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='selected_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
