# Generated by Django 6.1.1 on 2026-10-01 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('progress', '0004_quizanswer_selected_text'),
        ('quizzes', '0003_make_quiz_ownership_required'),
        ('subjects', '0003_topic_exam_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_items', to='lessons.lesson')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='progress.studyplan')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_items', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['scheduled_date', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='study_plan_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='studyplanitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('quiz__isnull', True)), models.Q(('lesson__isnull', True), ('quiz__isnull', False)), _connector='OR'), name='study_plan_item_one_target'),
        ),
        migrations.AddConstraint(
            model_name='studyplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'scheduled_date', 'order'), name='unique_plan_day_item_order'),
        ),
    ]
