# Generated by Django 6.1.1 on 2026-10-02 00:35

import django.db.models.deletion
from django.db import migrations, models


def migrate_study_plan_items(apps, schema_editor):
    StudyPlanItem = apps.get_model("progress", "StudyPlanItem")
    Quiz = apps.get_model("quizzes", "Quiz")
    Question = apps.get_model("questions", "Question")
    Topic = apps.get_model("subjects", "Topic")
    database = schema_editor.connection.alias

    for item in StudyPlanItem.objects.using(database).all().iterator():
        if item.quiz_id:
            quiz = Quiz.objects.using(database).filter(pk=item.quiz_id).first()
            item.item_type = "quiz"
            item.topic_id = quiz.topic_id if quiz else None
        else:
            item.item_type = "lesson"
            item.topic_id = Question.objects.using(database).filter(
                lesson_id=item.lesson_id,
                is_active=True,
                topic__is_active=True,
            ).order_by("id").values_list("topic_id", flat=True).first()
            if item.topic_id is None:
                item.topic_id = Quiz.objects.using(database).filter(
                    lesson_id=item.lesson_id,
                    is_active=True,
                    topic__is_active=True,
                ).order_by("id").values_list("topic_id", flat=True).first()
            if item.topic_id is None:
                item.topic_id = Topic.objects.using(database).filter(
                    subject_id=item.plan.subject_id,
                    is_active=True,
                ).order_by("name").values_list("id", flat=True).first()
        item.completed = item.completed_at is not None
        item.save(update_fields=["item_type", "topic", "completed"], using=database)


def restore_legacy_quiz_targets(apps, schema_editor):
    StudyPlanItem = apps.get_model("progress", "StudyPlanItem")
    Quiz = apps.get_model("quizzes", "Quiz")
    database = schema_editor.connection.alias

    for item in StudyPlanItem.objects.using(database).filter(item_type="quiz").iterator():
        quiz_id = Quiz.objects.using(database).filter(
            subject_id=item.plan.subject_id,
            topic_id=item.topic_id,
        ).order_by("id").values_list("id", flat=True).first()
        item.quiz_id = quiz_id
        item.save(update_fields=["quiz"], using=database)


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('progress', '0005_studyplan_studyplanitem_and_more'),
        ('subjects', '0003_topic_exam_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyplan',
            options={'ordering': ['target_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='studyplanitem',
            options={'ordering': ['scheduled_date', 'order']},
        ),
        migrations.RemoveConstraint(
            model_name='studyplan',
            name='study_plan_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='studyplanitem',
            name='study_plan_item_one_target',
        ),
        migrations.RenameField(
            model_name='studyplan',
            old_name='start_date',
            new_name='target_date',
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='item_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('flashcard_review', 'Flashcard review'), ('mistake_review', 'Mistake review')], default='lesson', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyplanitem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_items', to='subjects.topic'),
        ),
        migrations.RunPython(migrate_study_plan_items, restore_legacy_quiz_targets),
        migrations.AddConstraint(
            model_name='studyplanitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'lesson'), ('lesson__isnull', False)), models.Q(models.Q(('item_type', 'lesson'), _negated=True), ('lesson__isnull', True)), _connector='OR'), name='study_plan_item_lesson_target'),
        ),
        migrations.AddConstraint(
            model_name='studyplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_type', 'lesson'), ('topic__isnull', False), _connector='OR'), name='study_plan_item_topic_target'),
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='title',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studyplanitem',
            name='quiz',
        ),
    ]
