# Generated by Django 6.1.1 on 2026-10-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_study_plan_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
