# Generated by Django 6.1.1 on 2026-09-16 01:23

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_question_ownership(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    Topic = apps.get_model("subjects", "Topic")

    for question in Question.objects.select_related("lesson__subject"):
        subject = question.lesson.subject
        topic_name = question.lesson.section_title or "General"
        topic, _ = Topic.objects.get_or_create(
            subject_id=subject.id,
            slug=slugify(topic_name) or "general",
            defaults={"name": topic_name},
        )
        question.subject_id = subject.id
        question.topic_id = topic.id
        question.save(update_fields=["subject", "topic"])


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('subjects', '0002_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.topic'),
        ),
        migrations.RunPython(populate_question_ownership, migrations.RunPython.noop),
    ]
