# Generated by Django 6.1.1 on 2026-10-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_make_question_ownership_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='match_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='format',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True / False'), ('short_answer', 'Short answer'), ('matching', 'Matching'), ('worded', 'Worded answer')], default='multiple_choice', max_length=30),
        ),
    ]
